version: '3'

networks:
  byfn:

services:

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:x86_64-1.1.0
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_CHAINCODE_KEEPALIVE=10
    command: /bin/bash
    volumes:
      - ./chaincode/demo1:/opt/gopath/src/github.com/demo1
      - ./chaincode/demo2:/opt/gopath/src/github.com/demo2
      - ./crypto-config:/opt/crypto-config
      - ./configtx:/opt/configtx
    extra_hosts:
      - orderer.fireflyc.im:192.168.100.10
      - peer0.org1.fireflyc.im:192.168.100.11
      - peer0.org2.fireflyc.im:192.168.100.12
    networks:
      - byfn

  peer0:
    container_name: peer0
    image: hyperledger/fabric-peer:x86_64-1.1.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${PROJECT_NAME}_byfn
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp

      - CORE_PEER_ID=peer0.org2.fireflyc.im
      - CORE_PEER_ADDRESS=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=Org2MSP

      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.fireflyc.im:8051
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org2.fireflyc.im/peers/peer0.org2.fireflyc.im/msp:/etc/hyperledger/peer/msp
      - /fabric/peer0.org2.fireflyc.im:/var/hyperledger/production:Z
    extra_hosts:
      - orderer.fireflyc.im:192.168.100.10
      - peer0.org1.fireflyc.im:192.168.100.11
      - peer0.org2.fireflyc.im:192.168.100.12
    ports:
      - 8051:7051
      - 8053:7053
    networks:
      - byfn

  peer1:
    container_name: peer1
    image: hyperledger/fabric-peer:x86_64-1.1.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${PROJECT_NAME}_byfn
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp

      - CORE_PEER_ID=peer1.org2.fireflyc.im
      - CORE_PEER_ADDRESS=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=Org2MSP

      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.fireflyc.im:8051
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org2.fireflyc.im/peers/peer1.org2.fireflyc.im/msp:/etc/hyperledger/peer/msp
      - /fabric/peer1.org2.fireflyc.im:/var/hyperledger/production:Z
    extra_hosts:
      - orderer.fireflyc.im:192.168.100.10
      - peer0.org1.fireflyc.im:192.168.100.11
      - peer0.org2.fireflyc.im:192.168.100.12
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      - byfn