OrdererOrgs:
  - Name: Orderer
    Domain: fireflyc.im
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.fireflyc.im
    EnableNodeOUs: false
    Template:
      Count: 2
    Users:
      Count: 1
      
  - Name: Org2
    Domain: org2.fireflyc.im
    EnableNodeOUs: false
    Template:
      Count: 2
    Users:
      Count: 1